### PR TITLE
Fix build, drop deprecated handlers, and prepare new release 1.14.0

### PR DESCRIPTION
**Pull request by gwarf**
- Fix build.
- Drop some deprecated providers.
- Prepare new release 1.14.0:

```markdown
## [1.14.0] - 2023-04-11

## Added

- Drop some deprecated providers (gatekeeper, gridice, lbserver, wmproxy). (#3) (Baptiste Grenier)
- Lint code. (#3) (Enol Fernandez) (Baptiste Grenier)
- Add Community files and GitHub actions. (#2) (Baptiste Grenier)
- Build and release using CentOS 7, AlmaLinux 8 and 9. (#2) (Baptiste Grenier)
```

### CODE REVIEW

**Comment by gwarf** [comment]
So before releasing, it seems we may have to fix various things. Maybe also the good time to remove some deprecated stuff, like AMGA...

**Comment by gwarf** [comment]
So we have all those providers, let's tick the ones we want to keep:
* [x] [glite-info-glue2-endpoint](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-glue2-endpoint)
* [x] [glite-info-service-amga](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-amga)
* [ ] [glite-info-service-frontier](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-frontier)
* [x] [glite-info-service-myproxy](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-myproxy)
* [x] [glite-info-service-voms](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-voms)
* [x] [glite-info-glue2-multi](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-glue2-multi)
* [x] [glite-info-service-argus](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-argus)
* [ ] [glite-info-service-gatekeeper](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-gatekeeper)
* [x] [glite-info-service-rtepublisher](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-rtepublisher)
* [x] [glite-info-service-voms-admin](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-voms-admin)
* [x] [glite-info-glue2-service](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-glue2-service)
* [x] [glite-info-service-bdii](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-bdii)
* [x] [glite-info-service-glue2](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-glue2)
* [x] [glite-info-service-squid](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-squid)
* [x] [glite-info-service-voms-wrapper](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-voms-wrapper)
* [x] [glite-info-glue2-simple](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-glue2-simple)
* [x] [glite-info-service-cream](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-cream)
* [x] [glite-info-service-glue2-beta](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-glue2-beta)
* [x] [glite-info-service-status](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-status)
* [ ] [glite-info-service-wmproxy](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-wmproxy)
* [x] [glite-info-glue2-voms](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-glue2-voms)
* [x] [glite-info-service-dcache](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-dcache)
* [ ] [glite-info-service-gridice](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-gridice)
* [x] [glite-info-service-test](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-test)
* [x] [glite-info-service](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service)
* [x] [glite-info-service-dpm](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-dpm)
* [ ] [glite-info-service-lbserver](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-lbserver)
* [x] [glite-info-service-vobox](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-vobox)

**Comment by enolfc** [comment]
> So we have all those providers:
> ...

do we want to keep all of these?
I mean do we tick the box for those that we want to keep or the ones we want to remove

**Comment by gwarf** [comment]
Good point, let's agree to tick the ones we want to keep.

**Comment by enolfc** [comment]
This may help to decide:
```
$ ldapsearch -x -h lcg-bdii.egi.eu -p 2170 -b o=glue | grep "GLUE2ServiceType" | sort -u
GLUE2ServiceType: DPM
GLUE2ServiceType: IaaS
GLUE2ServiceType: MyProxy
GLUE2ServiceType: SRM
GLUE2ServiceType: bdii_site
GLUE2ServiceType: bdii_top
GLUE2ServiceType: dpm
GLUE2ServiceType: lcg-file-catalog
GLUE2ServiceType: lcg-local-file-catalog
GLUE2ServiceType: org.dcache.storage
GLUE2ServiceType: org.glite.AMGA
GLUE2ServiceType: org.glite.Argus
GLUE2ServiceType: org.glite.Argus.PAP
GLUE2ServiceType: org.glite.FileTransfer
GLUE2ServiceType: org.glite.RTEPublisher
GLUE2ServiceType: org.glite.ce.CREAM
GLUE2ServiceType: org.glite.voms
GLUE2ServiceType: org.nordugrid.arex
GLUE2ServiceType: org.ogf.emies
GLUE2ServiceType: org.opensciencegrid.htcondorce
GLUE2ServiceType: storm
```

**Comment by gwarf** [comment]
we still have some AMGA reported?...

A few endpoints, not sure how they are really operating:
```shell
$ ldapsearch -LLL -x -h lcg-bdii.egi.eu -p 2170 -b o=glue "GLUE2ServiceType=org.glite.AMGA"
```

**Comment by gwarf** [comment]
There are also GLUE1 reports:
```shell
❯ ldapsearch -x -h lcg-bdii.egi.eu -p 2170 -b o=grid | grep "ServiceType" | sort -u
GlueServiceType: ARC-CE
GlueServiceType: HTCondorCE
GlueServiceType: MyProxy
GlueServiceType: SRM
GlueServiceType: bdii_site
GlueServiceType: bdii_top
GlueServiceType: data-location-interface
GlueServiceType: lcg-file-catalog
GlueServiceType: lcg-local-file-catalog
GlueServiceType: local-data-location-interface
GlueServiceType: org.glite.Argus.PAP
GlueServiceType: org.glite.Argus.PDP
GlueServiceType: org.glite.Argus.PEP
GlueServiceType: org.glite.RTEPublisher
GlueServiceType: org.glite.ce.CREAM
GlueServiceType: org.glite.voms
GlueServiceType: org.glite.voms-admin
GlueServiceType: org.opensciencegrid.htcondorce
GlueServiceType: xroot
```

**Comment by gwarf** [comment]
We can also search on the provider name:
```shell
$ ldapsearch -LLL -x -h lcg-bdii.egi.eu -p 2170 -b o=glue "GLUE2EntityOtherInfo=*InfoProviderName=glite-info-*" | grep InfoProviderName | sort -u
GLUE2EntityOtherInfo: InfoProviderName=glite-info-glue2-endpoint
GLUE2EntityOtherInfo: InfoProviderName=glite-info-glue2-service
```

So apparently very few providers are used here

**Comment by gwarf** [comment]
In fact if we are conservative, very few providers may be removed.
I'm really unsure here, not having proper knowledge on what is really still used or not :/
@paolini78, others what do you think?

**Comment by gwarf** [comment]
I feel those one may probably be quite safely removed:
- ~[glite-info-service-frontier](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-frontier)~: I've added it back, as I think it's linked to squid/CVMFS stuff,
- [glite-info-service-gatekeeper](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-gatekeeper) (still this is not empty: `ldapsearch -LLL -x -h lcg-bdii.egi.eu -p 2170 -b o=grid | grep -i gatekeeper | sort -u`)
- [glite-info-service-wmproxy](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-wmproxy)
- [glite-info-service-gridice](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-gridice)
- [glite-info-service-lbserver](https://github.com/EGI-Federation/glite-info-provider-service/blob/main/src/glite-info-service-lbserver)

**Comment by enolfc** [comment]
I added some more fixes for the linters, including ignoring 2 shellcheck errors, that I don't see an easy way out

**Review by enolfc — APPROVED** [review]
LGTM!
I didn't look too much into the perl code, but I would assume nothing is broken by the change.

**Comment by gwarf** [comment]
Thanks @enolfc ! Let's merge, we also assume that tests will trigger most possible issues.

**Pull request merged**
